from typing import Protocol
from uuid import UUID

from .user import User
from .organization import Organization
from .plan import Plan
from .analysis import Analysis
from .material import Material
from .material_list import MaterialList
from .material_item import MaterialItem

class UserRepository(Protocol):
    async def get_users(self) -> list[User]: ...
    async def get_user_by_id(self, id: int) -> User: ...
    async def create_user(self, request: User) -> User: ...
    async def update_user(self, id:  int, request: User) -> User: ...
    async def delete_user(self, id: int) -> None: ...
    async def user_existing(self, id: int) -> bool: ...

class OrganizationRepository(Protocol):
    async def get_organizations(self) -> list[Organization]: ...
    async def get_organization_by_id(self, id: int) -> Organization: ...
    async def create_organization(self, request: Organization) -> Organization: ...
    async def update_organization(self, id: int, request: Organization) -> Organization: ...
    async def delete_organization(self, id: int) -> None: ...
    async def user_existing(self, user_id: int) -> bool: ...
    async def organization_existing(self, id: int) -> bool: ...

class PlanRepository(Protocol):
    async def get_plans(self, organization_id: int) -> list[Plan]: ...
    async def get_plan_by_id(self, id: int) -> Plan: ...
    async def create_plan(self, request: Plan) -> Plan: ...
    async def delete_plan(self, id: int) -> None: ...
    async def organization_existing(self, organization_id: int) -> bool: ...
    async def plan_existing(self, id: int) -> bool: ...

class AnalysisRepository(Protocol):
    async def get_analyses(self, plan_id: int) -> list[Analysis]: ...
    async def get_analysis_by_id(self, id: UUID) -> Analysis | None: ...
    async def create_analysis(self, request: Analysis) -> Analysis: ...
    async def update_analysis(self, id: UUID, request: Analysis) -> None: ...
    async def plan_existing(self, plan_id: int) -> bool: ...

class MaterialRepository(Protocol):
    async def get_materials(self) -> list[Material]: ...
    async def get_material_by_id(self, id: int) -> Material: ...
    async def create_material(self, request: Material) -> Material: ...
    async def update_material(self, id: int, request: Material) -> Material: ...
    async def delete_material(self, id: int) -> None: ...

class MaterialListRepository(Protocol):
    async def create_material_list(self, request: MaterialList) -> MaterialList: ...

class MaterialItemRepository(Protocol):
    async def create_material_item(self, requests: list[MaterialItem]) -> list[MaterialItem]: ...
